# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

# Maybe one day this will work
#   "mac":
#     macos:
#       xcode: "9.0"
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - run:
#           command: |
#             . .circleci/cmake_test.sh

version: 2.1
jobs:
  "py310":
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_circleimg.sh
            . .circleci/python_test.sh

  "py311":
    docker:
      - image: circleci/python:3.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_circleimg.sh
            . .circleci/python_test.sh
  "py39":
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_circleimg.sh
            . .circleci/python_test.sh

  "gcc13":
    docker:
      - image: gcc:13
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/gcc_test.sh

  "gcc12":
    docker:
      - image: gcc:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/gcc_test.sh

  "gcc11":
    docker:
      - image: gcc:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/gcc_test.sh

  "gcclatest":
    docker:
      - image: gcc:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/gcc_test.sh

  "debian-bullseye-gcc":
    docker:
      - image: debian:bullseye
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_debian.sh
            . .circleci/gcc_test.sh

  "debian-bullseye-cmake":
    docker:
      - image: debian:bullseye
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_debian.sh
            . .circleci/cmake_test.sh

  "debian-bullseye-python":
    docker:
      - image: debian:bullseye
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_debian.sh
            pip install .
            python runtests.py -u

  "website-build":
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            git config --global user.email "docusaurus-bot@users.noreply.github.com"
            git config --global user.name "Website Deployment Script"
            echo "machine github.com login docusaurus-bot password $GITHUB_TOKEN_DOCUSAURUS_BOT" > ~/.netrc
            cd website && npm install && GIT_USER=docusaurus-bot npm run publish-gh-pages

workflows:
  version: 2
  build:
    jobs:
      - "py311"
      - "py310"
      - "py39"
      - "gcc13"
      - "gcc12"
      - "gcc11"
      - "gcclatest"
      - "website-build"
      - "debian-bullseye-gcc"
      - "debian-bullseye-cmake"
      - "debian-bullseye-python"
